name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Change working directory to where your Gradle project is located
      #      - name: Navigate to app directory
      #        run: cd app
      #        shell: bash

      # Use the Gradle Wrapper that exists in your project
      - name: Build with Gradle Wrapper
        run: ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Navigate to app directory
        run: cd app
        shell: bash

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          working-directory: app