name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        working-directory: ./app
        run: ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # Для GitHub Dependency Graph больше не нужно явное разрешение
      # Начиная с 2023 года это разрешение включено по умолчанию

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Submit dependencies
        uses: gradle/actions/dependency-submission@v4
        with:
          build-root-directory: 'app'
          # gradle-version: 8.5  # Раскомментируйте если нужно указать версию
